server:
  port: 9001

spring:
  profiles:
    active:
      on-profile: default

eureka:
  instance:
    prefer-ip-address: true
    hostname: discovery-service
  client:
    registerWithEureka: false
    fetchRegistry: false
    service-url:
      defaultZone: http://{eureka.instance.hostname}:${server.port}/eureka/

  server:
    waitTimeInMsWhenSyncEmpty: 5
