server:
  port: 9001

spring:
  profiles:
    active:
      on-profile: default

eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    service-url:
      defaultZone: http://discovery-service:9001/eureka/
  server:
    waitTimeInMsWhenSyncEmpty: 5
