server:
  port: 9001

spring:
  profiles:
    active:
      on-profile: default

eureka:
  instance:
    hostname: discovery
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:9001/eureka/
  server:
    waitTimeInMsWhenSyncEmpty: 5

management:
  endpoints:
    web:
      exposure:
        include: "*"
