spring:
  profiles:
    active:
      on-profile: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/account-service?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: '{cipher}187bab09ae65796ad5a42eeac49c5bd26d6e96c1a425db83bd5923a54c3c8c2f'
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  redis:
    host: localhost
    port: 6379
  mail:
    host: smtp.gmail.com
    port: 587
    username: '{cipher}37388080c2dd5830fab1246f750ca52d4032f2a0a02592102fdd72a69f079e8756b2ebaefd2c7c4bb45aba34daa93772'
    password: '{cipher}7336bec9da585658bf57bfd6fbc148ad4967d9b9a12f03a835d0ec34fce0133d44918355ee6de720ce481181628a2ed2'
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eurekaserver:9001/eureka/